### ISSUE TITLE
Development Bug Tracker

### ISSUE THREAD

**Issue by minecraft-anarchy** [minecraft-anarchy/LightweightTeleport#1]
can you let /tp without arguments show /tp help (thats kind of a unix command line tool standard)
/tp poi is missing in help text
/tp cooldown gives no output if there is no cooldown (should be 0)
/tp wild doesnt work - I think it fails on searching a proper teleportable point? I had some trouble with that when I was working on it, but dont see any errors in server log either
/tp poi should say "List of avaialble Points Of Interest:", and /tp poi list should be available as an alias (actually /tp poi should be the alias for /tp poi list
please comment out "home" and "sethome" (but keep the code) - its to overkill imho. tp bed should do for regular players. but pls keep the code.
/tp gps 80 80 80 does not work
I think I had a config with pre-defined pois like spawn, nether, end, where nether and end only work if you have the acchivement for the end.. is that code still somewhere in what I send you?
tp accept / deny / to I couldnt test as my gf is busy atm x)
if /tp bed and the bed is missing, pls print this default message "your bed is missing or obstructed"

[] I'm admin (op) but the cooldown affects me
[] what is the POI "Me" ?
[]

**Comment by minecraft-anarchy** [comment]
latest build (0.3-alpha) bug reports:

- [ ] `/tp wild` teleports into solid blocks / water / air / ...
- [ ] `/tp` with no args throws an error (same for /tp help)
- [ ] added POIs are shown with the first letter capitalized in the list (`/tp poi`), even when added with first letter lowercase
- [ ] `/tp toa` is not in the autocomplete list (but `/tp toa ACCEPT` and DENY is)
- [ ] `/tp toa deny` after they have been accepted says "you already accepted"

- [ ] `/tp to <my-own-player-name>` asks and then immediately says the accept period expired. maybe we should just reject if destination_player == own_player_name
- [ ] "Asking <playername>to" <- here a whitespace is missing in the text
- [ ] `/tp to` / `tp accept` does not work (tested with two op's) (see pic below)

also `/tp gps` should accept the dimension at the end (`/tp gps 80 80 80 nether`) - but that wasn't specified initially, so its an extra feature ;)

**Comment by minecraft-anarchy** [comment]
- [ ] `/tp toa` should print the current status (accepted / not accepted)
- [ ] `/tp setpoi FOObar` should return `FOObar` for `/tp poi`
- [ ] what are respawn anchors? should they respond to `/tp bed`?
- [ ] `tp-wild-radius: 1500` but I get teleported to around ~2500 blocks out
- [ ] `/tp gps 80 80 80 [overworld, nether, end]` returns "Unknown dimension". Maybe that is because spigot is using different world names I think I remember? There was a function to return the names of the "nether" I think I remember.. Think I had a similar problem once.
- [ ] I'm not sure if `tp generatelocations` does anything yet? If so, the config file should contain a number of locations to generate. After running the command (and waiting a bit), andomlocations.yml is empty. Maybe while the command is running, it should return every now and then how many locations it found so far, so there is kind of a "progress status update". Maybe like every 5 locations or so, not sure how fast that all is.

**Comment by Wmorales01** [comment]
- [ ] TP Cooldown is currently displayed in minutes, it should be displayed in seconds.
- [ ] `/tp generatelocations` is storing only one location even though it is searching more than one.
- [ ] Remove safe locations from `/tp gps`.
- [ ] Prevent non OP Players from issuing `/tp wild` if there are no locations in the database, if it is an OP player the plugin should manually execute the search.
- [ ] If `/tp gps` doesn't receive a world parameter it should take current world as default.
- [ ] If `/tp gps` receives a wrong world parameter it should send a message for missing key and missing value depending in the current situation.

**Comment by minecraft-anarchy** [comment]
things to check when permission plugin is working:

- [ ] Prevent non OP Players from issuing /tp wild if there are no locations in the database, if it is an OP player the plugin should manually execute the search.
- [ ] TP Cooldown is currently displayed in minutes, it should be displayed in seconds.
- [ ]  "Asking to" <- here a whitespace is missing in the text
- [ ] regular users (non ops) dont have any autocomplete after /tp - however /tp poi <auto-complete-here works, for example only OPs should be able to use "setpoi" and "delpoi"
- [ ] check particle effects
- [ ] check particle effects for death
- [ ] check 5s delay & moving before teleport operation
- [ ] check users can only see what they can use in /tp help & autocomplete

**Comment by Wmorales01** [comment]
- [ ] During tp wild location generation, check if X amount of chunks around the location is generated, if they are, look for another location. This way player's won't be teleported to other player's bases

**Comment by Wmorales01** [comment]
- [ ] Schedule a task every 24 hours to generate new wild locations and avoid tping to already explored locations.
